### ISSUE TITLE
Damage modifier as mission parameter

### ISSUE THREAD

**Issue by kju** [ConnorAU/A3GunGame#1]
so have a HD EH added to infantry and you have a multiplier
say 0.25, 0.5, 1, 1.5, 2, 2.5, 5, 10

in other words to have all weapons be less or more lethal

in case you want more deadly or more long lasting firefights

**Comment by ConnorAU** [comment]
Added https://github.com/ConnorAU/A3GunGame/commit/03f73196099dfc5c4b089a23f243dfb7b367e380
